### ISSUE TITLE
tokenLoop error 

### ISSUE THREAD

**Issue by tfrischb** [BlockchainTokenSniper/BSCTokenSniper#70]
[ERROR] tokenLoop error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 596, in tokenLoop
  File "C:\Users\timmf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\_utils\filters.py", line 160, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "C:\Users\timmf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\timmf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\timmf\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}

**Comment by BlockchainTokenSniper** [comment]
Use latest version in telegram testing group
