### ISSUE TITLE
tokenLoop error

### ISSUE THREAD

**Issue by muhababuzeid** [BlockchainTokenSniper/BSCTokenSniper#72]
Hello, 

I am getting the message below, it keeps repeating for some time, sometimes it stops and the program works fine again, sometimes I quit and run again.

Thank you.

Edit: I am using v1.3

===============================================================================

[ERROR] tokenLoop error, please notify dev:
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 596, in tokenLoop
  File "C:\Program Files\Python39\lib\site-packages\web3\_utils\filters.py", line 160, in get_new_entries
    log_entries = self._filter_valid_entries(self.eth_module.get_filter_changes(self.filter_id))
  File "C:\Program Files\Python39\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Program Files\Python39\lib\site-packages\web3\manager.py", line 187, in request_blocking
    return self.formatted_response(response,
  File "C:\Program Files\Python39\lib\site-packages\web3\manager.py", line 168, in formatted_response
    raise ValueError(response["error"])
ValueError: {'code': -32000, 'message': 'filter not found'}

**Comment by nickyoung92** [comment]
I have same issue. Did you find fix?

**Comment by BlockchainTokenSniper** [comment]
Use v1.4 in telegram group
