### ISSUE TITLE
buyToken error, please notify dev

### ISSUE THREAD

**Issue by udemethegrtman** [BlockchainTokenSniper/BSCTokenSniper#76]
```
Traceback (most recent call last):
  File "BSCTokenSniper.py", line 356, in Buy
  File "C:\Users\GM Digital\AppData\Local\Programs\Python\Python39\lib\site-packages\eth_utils\decorators.py", line 18, in _wrapper
    return self.method(obj, *args, **kwargs)
  File "C:\Users\GM Digital\AppData\Local\Programs\Python\Python39\lib\site-packages\eth_account\account.py", line 734, in sign_transaction
    raise TypeError("from field must match key's %s, but it was %s" % (
TypeError: from field must match key's 0x5A002fDd6D66bEa4579Ba20a34f923Ec0ffa26, but it was 0x3d47c85BBC7A77f7da4eA9Ec226922278Bf9df

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BSCTokenSniper.py", line 359, in Buy
TypeError: can only concatenate str (not "TypeError") to str
```

**Comment by BlockchainTokenSniper** [comment]
What version of bot are u using here?

**Comment by udemethegrtman** [comment]
1.3

**Comment by BlockchainTokenSniper** [comment]
Use v1.4 in telegram group
